{
 "title": "forward-auth",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "query": {
     "query": "label_values(http_request_duration_seconds{app=\"forward-auth\"},quantile)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(forward_auth_session_count,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (forward_auth_session_count{instance=~\"^$instance$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (forward_auth_session_count{instance=~\"^$instance$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "forwardAuth request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_requests_total{app=\"forward-auth\",handler=\"forwardauth\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "forwardAuth request latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds{instance=~\"^$instance$\", handler=\"forwardauth\", quantile=\"$percentile\"}) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active login states",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(forward_auth_state_count{instance=~\"^$instance$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active login states",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(forward_auth_state_count{instance=~\"^$instance$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_requests_total{instance=~\"^$instance$\", handler=\"login\",code=\"303\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "invalid login attempts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_requests_total{instance=~\"^$instance$\", handler=\"login\",code!=\"303\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "redis operations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum (rate(redis_commands_total{namespace=\"forward-auth\"}[$__rate_interval])) by (cmd)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}